const menuButton=document.querySelector('.menu-toggle');const navigation=document.querySelector('.site-nav');menuButton?.addEventListener('click',()=>{const open=menuButton.getAttribute('aria-expanded')==='true';menuButton.setAttribute('aria-expanded',String(!open));menuButton.setAttribute('aria-label',open?'Open navigation':'Close navigation');navigation?.classList.toggle('open',!open);document.body.classList.toggle('menu-open',!open)});navigation?.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{navigation.classList.remove('open');menuButton?.setAttribute('aria-expanded','false');menuButton?.setAttribute('aria-label','Open navigation');document.body.classList.remove('menu-open')}));

const workImages=[...document.querySelectorAll('.image-button')];const lightbox=document.querySelector('#lightbox');const lightboxImage=lightbox?.querySelector('img');const lightboxCaption=lightbox?.querySelector('p');let activeIndex=0;function showImage(index){if(!lightbox||!lightboxImage||!lightboxCaption||!workImages.length)return;activeIndex=(index+workImages.length)%workImages.length;const source=workImages[activeIndex].querySelector('img');lightboxImage.src=source.src;lightboxImage.alt=source.alt;lightboxCaption.textContent=workImages[activeIndex].closest('figure')?.querySelector('h3')?.textContent||''}workImages.forEach((button,index)=>button.addEventListener('click',()=>{showImage(index);lightbox?.showModal()}));lightbox?.querySelector('.lightbox-close')?.addEventListener('click',()=>lightbox.close());lightbox?.querySelector('.prev')?.addEventListener('click',()=>showImage(activeIndex-1));lightbox?.querySelector('.next')?.addEventListener('click',()=>showImage(activeIndex+1));lightbox?.addEventListener('click',event=>{if(event.target===lightbox)lightbox.close()});document.addEventListener('keydown',event=>{if(!lightbox?.open)return;if(event.key==='Escape')lightbox.close();if(event.key==='ArrowLeft')showImage(activeIndex-1);if(event.key==='ArrowRight')showImage(activeIndex+1)});

const contactForm=document.querySelector('#contact-form');const formMessage=document.querySelector('#form-message');contactForm?.addEventListener('submit',event=>{if(!contactForm.checkValidity()){event.preventDefault();contactForm.reportValidity();if(formMessage)formMessage.textContent='Please complete all required fields.';return}if(contactForm.action.includes('REPLACE_WITH_FORM_ID')){event.preventDefault();if(formMessage)formMessage.textContent='This form is not connected yet. Add your Formspree form ID before publishing.'}});const year=document.querySelector('#year');if(year)year.textContent=new Date().getFullYear();

const productDialog=document.querySelector('#product-dialog');document.querySelector('.shop-product-open')?.addEventListener('click',()=>productDialog?.showModal());productDialog?.querySelector('.product-dialog-close')?.addEventListener('click',()=>productDialog.close());productDialog?.addEventListener('click',event=>{if(event.target===productDialog)productDialog.close()});

const eucalyptusDialog=document.querySelector('#eucalyptus-dialog');document.querySelector('.eucalyptus-product-open')?.addEventListener('click',()=>eucalyptusDialog?.showModal());eucalyptusDialog?.querySelector('.product-dialog-close')?.addEventListener('click',()=>eucalyptusDialog.close());eucalyptusDialog?.addEventListener('click',event=>{if(event.target===eucalyptusDialog)eucalyptusDialog.close()});

const sycamoreDialog=document.querySelector('#sycamore-dialog');document.querySelector('.sycamore-product-open')?.addEventListener('click',()=>sycamoreDialog?.showModal());sycamoreDialog?.querySelector('.product-dialog-close')?.addEventListener('click',()=>sycamoreDialog.close());sycamoreDialog?.addEventListener('click',event=>{if(event.target===sycamoreDialog)sycamoreDialog.close()});

const coastersDialog=document.querySelector('#coasters-dialog');document.querySelector('.coasters-product-open')?.addEventListener('click',()=>coastersDialog?.showModal());coastersDialog?.querySelector('.product-dialog-close')?.addEventListener('click',()=>coastersDialog.close());coastersDialog?.addEventListener('click',event=>{if(event.target===coastersDialog)coastersDialog.close()});

const redwoodDialog=document.querySelector('#redwood-dialog');document.querySelector('.redwood-product-open')?.addEventListener('click',()=>redwoodDialog?.showModal());redwoodDialog?.querySelector('.product-dialog-close')?.addEventListener('click',()=>redwoodDialog.close());redwoodDialog?.addEventListener('click',event=>{if(event.target===redwoodDialog)redwoodDialog.close()});

const bowlsDialog=document.querySelector('#bowls-dialog');document.addEventListener('click',event=>{const button=event.target.closest?.('.bowls-product-open');if(!button)return;event.stopPropagation();bowlsDialog?.showModal()},true);bowlsDialog?.querySelector('.product-dialog-close')?.addEventListener('click',()=>bowlsDialog.close());bowlsDialog?.addEventListener('click',event=>{if(event.target===bowlsDialog)bowlsDialog.close()});
